// Generated by https://quicktype.io

export interface Store {
    state:     State;
    commit (method: string, payload: any): void;
    dispatch (method: string, payload: any): void;
}

export interface State {
    members:  Member[];
    families: Family[];
    localization: { [key: string]: string };
}

export interface Family {
    id:          string;
    name:        string;
    street:      string;
    houseNumber: string;
    city:        string;
    zip:         string;
}

export interface Member {
    id:         string;
    firstName:  string;
    middleName?: string;
    lastName:   string;
    role:       string;
    familyId:   string;
}

export interface UpdateParam {
    id: string;
    property: string;
    value: string;
}
export interface DeleteParam {
    id: string;
}
export interface Component {
    $store: Store;
}